-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
    );

-- Таблица платформ
CREATE TABLE IF NOT EXISTS streaming_platforms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR(255) NOT NULL

    );

-- Таблица подписок
CREATE TABLE IF NOT EXISTS subscriptions (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,   -- При удалении пользователя удаляем и его друзей
    platform_id BIGINT REFERENCES streaming_platforms(id) ON DELETE CASCADE -- При удалении друга, удаляем связи
);